alias: Toggle light when dimmer is used
description: Toggles the light and adjusts brightness with ZHA dimmer long presses.
triggers:
  - device_id: bd9c9d9b4647b1423446b74d4fbf71d9
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
    id: toggle
  - device_id: bd9c9d9b4647b1423446b74d4fbf71d9
    domain: zha
    type: remote_button_long_press
    subtype: dim_up
    trigger: device
    id: brightness_increase
  - device_id: bd9c9d9b4647b1423446b74d4fbf71d9
    domain: zha
    type: remote_button_long_press
    subtype: dim_down
    trigger: device
    id: brightness_decrease
  - device_id: bd9c9d9b4647b1423446b74d4fbf71d9
    domain: zha
    type: remote_button_long_release
    subtype: dim_up
    trigger: device
    id: brightness_increase_release
  - device_id: bd9c9d9b4647b1423446b74d4fbf71d9
    domain: zha
    type: remote_button_long_release
    subtype: dim_down
    trigger: device
    id: brightness_decrease_release

conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: toggle
        sequence:
          - action: light.toggle
            target:
              device_id: 0bfb9e1cc92f40d7c20f69353e62c060
      - conditions:
          - condition: trigger
            id: brightness_increase
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - action: light.turn_on
                  target:
                    device_id: 0bfb9e1cc92f40d7c20f69353e62c060
                  data:
                    brightness_step_pct: 2
                    transition: 0.2
                - delay: "00:00:00.2"
      - conditions:
          - condition: trigger
            id: brightness_decrease
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - action: light.turn_on
                  target:
                    device_id: 0bfb9e1cc92f40d7c20f69353e62c060
                  data:
                    brightness_step_pct: -2
                    transition: 0.2
                - delay: "00:00:00.2"

mode: restart